<Project>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Condition="!Exists('packages.config')" Version="6.7.0" PrivateAssets="all"/>
  </ItemGroup>
  <PropertyGroup>
    <Company>BrycensRanch and ShareX Team</Company>
    <Product>SnapX</Product>
    <Title>SnapX</Title>
    <Description>Capture, share, and boost productivity. All in one.</Description>
    <Copyright>Copyright (c) 2026 BrycensRanch and ShareX Team</Copyright>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <IncludeDebugSymbolsProjectOutputGroup>false</IncludeDebugSymbolsProjectOutputGroup>
    <Optimize>true</Optimize>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <GitVersionTargetFramework>$(TargetFramework)</GitVersionTargetFramework>
    <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>
    <RollForward>LatestMajor</RollForward>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="!Exists('.git')">
    <UpdateAssemblyInfo>false</UpdateAssemblyInfo>
    <DisableGitVersionTask>true</DisableGitVersionTask>
  </PropertyGroup>
  <PropertyGroup>
    <TargetLinux>false</TargetLinux>
    <TargetWindows>false</TargetWindows>
    <TargetMacOS>false</TargetMacOS>
    <TargetFreeBSD>false</TargetFreeBSD>
    <TargetDesktop>false</TargetDesktop>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.Contains('browser'))">
    <DefineConstants>$(DefineConstants);BROWSER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'false' and
        (
            $([System.String]::Copy($(RuntimeIdentifier)).StartsWith('linux'))
            or $(RuntimeIdentifier.Contains('ubuntu'))
            or $(RuntimeIdentifier.Contains('debian'))
            or $(RuntimeIdentifier.Contains('fedora'))
            or $(RuntimeIdentifier.Contains('alpine'))
            or $(RuntimeIdentifier.Contains('arch'))
            or $(RuntimeIdentifier.Contains('rhel'))
            or $(RuntimeIdentifier.Contains('centos'))
            or $(RuntimeIdentifier.Contains('opensuse'))
        )
    )
    or
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'true' and
        $([MSBuild]::IsOSPlatform('Linux'))
    )
">
    <TargetLinux>true</TargetLinux>
  </PropertyGroup>


  <PropertyGroup Condition="
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'false' and
        $([System.String]::Copy($(RuntimeIdentifier)).StartsWith('win')))
    or
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'true' and
        $([MSBuild]::IsOSPlatform('Windows')))
">
    <TargetWindows>true</TargetWindows>
    <TargetFramework>$(TargetFramework)-windows10.0.26100.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'false' and
        $([System.String]::Copy($(RuntimeIdentifier)).StartsWith('osx')))
    or
    ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'true' and
        $([MSBuild]::IsOSPlatform('OSX')))
">
    <TargetMacOS>true</TargetMacOS>
  </PropertyGroup>

  <PropertyGroup Condition="
    (
        ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'false' and
            $([System.String]::Copy($(RuntimeIdentifier)).StartsWith('freebsd')))
        or
        ('$([System.String]::IsNullOrEmpty($(RuntimeIdentifier)))' == 'true' and
            $([MSBuild]::IsOSPlatform('FreeBSD')))
        or
        ('$(SNAPX_PRETEND_FREEBSD)' == '1')
    )
">
    <TargetFreeBSD>true</TargetFreeBSD>
    <DefineConstants>$(DefineConstants);FREEBSD</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetMacOS)' == 'true' and ( '$(OutputType)' == 'Exe' or '$(OutputType)' == 'WinExe' )">
    <LinkerArg Include="-Wl,-ld_classic" />
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetWindows)' == 'true' and ( '$(OutputType)' == 'Exe' or '$(OutputType)' == 'WinExe' )">
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
    <UseRIDGraph>true</UseRIDGraph>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Platforms>x64;arm64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <TargetDesktop Condition="'$(TargetWindows)' == 'true'
                           or '$(TargetLinux)' == 'true'
                           or '$(TargetMacOS)' == 'true'
                           or '$(TargetFreeBSD)' == 'true'">true</TargetDesktop>
  </PropertyGroup>
</Project>
